# Site settings
title: Martijn van Laar
description: Resume Martijn van Laar
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Martijn van Laar
user_description: I'm a data scientist with an eye for the technical side of things. I love solving problems (even when the problem is a messy dataset) and using my technical skills to (help) unlock insights from data.
user_title: Data Scientist
email: hi@martijnvanlaar.nl
twitter_username: martijnvanlaar
github_username:  martvl
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
